version: "3.8"

networks:
  my-bridge:
    external:
      name: host

services:
  spring-backend:
    build: .
    image: spring-backend
    container_name: spring-backend
    restart: always
    networks:
      - host
    ports:
      - 8080:8080
